# Generated by Django 3.1.3 on 2020-12-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw20', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('profession', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
