# Generated by Django 3.1.3 on 2020-12-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw22', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='musicband',
            name='foundation_year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
