# Generated by Django 3.1.3 on 2020-12-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw22', '0003_auto_20201206_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hw22.musicband'),
        ),
    ]
