# Generated by Django 3.1.3 on 2020-12-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw22', '0004_track_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicband',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hw22.musicband'),
        ),
    ]
