# Generated by Django 3.1.3 on 2020-12-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw22', '0006_auto_20201206_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicband',
            name='album',
        ),
    ]
