# Generated by Django 3.1.3 on 2020-12-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw22', '0004_auto_20201206_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('pages_amount', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='book',
            field=models.ManyToManyField(default=None, null=True, to='cw22.Book'),
        ),
    ]
