# Generated by Django 3.1.4 on 2020-12-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201221_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.TextField(default=None),
        ),
    ]
