# Generated by Django 3.1.4 on 2020-12-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201224_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sphere',
            name='sphere',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
