# Generated by Django 3.1.4 on 2020-12-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201224_0803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sphere',
        ),
    ]
