# Generated by Django 3.1.4 on 2020-12-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_sphere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sphere',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
