# Generated by Django 3.1.4 on 2020-12-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201225_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
