# Generated by Django 3.1.4 on 2020-12-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_cv_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
